"""Initial schema setup

Revision ID: 61cdcd190213
Revises:
Create Date: 2026-08-11 01:36:58.517807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61cdcd190213"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_batches",
        sa.Column("cycle_index", sa.Integer(), nullable=False),
        sa.Column("invoice_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_batches_id"), "invoice_batches", ["id"], unique=False)
    op.create_table(
        "schedule_cycles",
        sa.Column("cycle_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invoice_count", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedule_cycles_cycle_index"), "schedule_cycles", ["cycle_index"], unique=True
    )
    op.create_index(op.f("ix_schedule_cycles_id"), "schedule_cycles", ["id"], unique=False)
    op.create_table(
        "transfer_records",
        sa.Column("stark_transfer_id", sa.String(), nullable=True),
        sa.Column("stark_invoice_id", sa.String(), nullable=True),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("fee", sa.Integer(), nullable=False),
        sa.Column("net_amount", sa.Integer(), nullable=False),
        sa.Column("target_bank_code", sa.String(), nullable=False),
        sa.Column("target_branch", sa.String(), nullable=False),
        sa.Column("target_account", sa.String(), nullable=False),
        sa.Column("target_name", sa.String(), nullable=False),
        sa.Column("target_tax_id", sa.String(), nullable=False),
        sa.Column("target_account_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transfer_records_event_id"), "transfer_records", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_transfer_records_id"), "transfer_records", ["id"], unique=False)
    op.create_index(
        op.f("ix_transfer_records_stark_invoice_id"),
        "transfer_records",
        ["stark_invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transfer_records_stark_transfer_id"),
        "transfer_records",
        ["stark_transfer_id"],
        unique=False,
    )
    op.create_table(
        "webhook_events",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("subscription", sa.String(), nullable=True),
        sa.Column("log_type", sa.String(), nullable=True),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhook_events_event_id"), "webhook_events", ["event_id"], unique=True)
    op.create_index(op.f("ix_webhook_events_id"), "webhook_events", ["id"], unique=False)
    op.create_table(
        "invoice_records",
        sa.Column("stark_invoice_id", sa.String(), nullable=True),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("tax_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["invoice_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_records_id"), "invoice_records", ["id"], unique=False)
    op.create_index(
        op.f("ix_invoice_records_stark_invoice_id"),
        "invoice_records",
        ["stark_invoice_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_records_stark_invoice_id"), table_name="invoice_records")
    op.drop_index(op.f("ix_invoice_records_id"), table_name="invoice_records")
    op.drop_table("invoice_records")
    op.drop_index(op.f("ix_webhook_events_id"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_event_id"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_transfer_records_stark_transfer_id"), table_name="transfer_records")
    op.drop_index(op.f("ix_transfer_records_stark_invoice_id"), table_name="transfer_records")
    op.drop_index(op.f("ix_transfer_records_id"), table_name="transfer_records")
    op.drop_index(op.f("ix_transfer_records_event_id"), table_name="transfer_records")
    op.drop_table("transfer_records")
    op.drop_index(op.f("ix_schedule_cycles_id"), table_name="schedule_cycles")
    op.drop_index(op.f("ix_schedule_cycles_cycle_index"), table_name="schedule_cycles")
    op.drop_table("schedule_cycles")
    op.drop_index(op.f("ix_invoice_batches_id"), table_name="invoice_batches")
    op.drop_table("invoice_batches")
    # ### end Alembic commands ###
